
---
output:
  html_vignette:
    mathjax: null
    jquery: null
    smart: no
    keep_md: TRUE
---

  
```{r setup, echo=FALSE, results='hide', warning=FALSE}
library(knitr, quietly = TRUE)
library(printr, quietly = TRUE)
opts_chunk$set(message=FALSE, warning=FALSE, out.width="100%", fig.retina = 1, fig.align='center', dev='png', dev.args=list(pointsize=10, antialias='cleartype'), tidy=FALSE)
options(width=300, stringsAsFactors=FALSE)

knit_hooks$set(htmlcap = function(before, options, envir) {
  if(!before) {
    paste('<p class="caption" style="font-size:85%; font-style: italic; font-weight: bold;">',options$htmlcap,"</p><hr>",sep="")
  }
})
```


Extracting NASIS Rules/Evaluations
========================================

```{r}
library(soilDB)
library(RODBC)
library(XML)
library(plyr)
library(data.tree)
library(digest)


## TODO: finish evaluation parsing functions


# source local functions
source('local-functions.R')

# re-load cached data
# getAndCacheData()

# load cached data
load('cached-NASIS-data.Rda')

###
### evaluation curves
###

## TODO: someimes the property min/max values are crazy

## arbitrary curve: example: Storie Index C factor 
e <- evals[evals$evalname == '*Storie Factor C Slope 0 to 100%', ]
res <- extractEvalCurve(e)
s <- seq(e$propmin, e$propmax, length.out = 100)
plot(s, res(s), type='l', xlab='domain', ylab='fuzzy rating', main=e$evaluationtype)

## sigmoid:
e <- evals[evals$evalname == 'SAR, <.5, 0-100cm (0 to 40")', ]
res <- extractEvalCurve(e)
s <- seq(e$propmin, e$propmax, length.out = 25)
plot(s, res(s), type='l', xlab='domain', ylab='fuzzy rating', main=e$evaluationtype)

## arbitrary linear
e <- evals[evals$evalname == 'GRL - EC maximum in depth 25 to 50 cm (NV)', ]
res <- extractEvalCurve(e)
s <- seq(e$propmin, e$propmax, length.out = 25)
plot(s, res(s), type='l', xlab='domain', ylab='fuzzy rating', main=e$evaluationtype)

## crisp:
e <- evals[evals$evalname == 'Soil pH (water) >= 4.5 and <= 8.4, 0-100cm', ]
res <- extractEvalCurve(e)
s <- seq(e$propmin, e$propmax, length.out = 25)
plot(s, res(s), type='l', xlab='domain', ylab='fuzzy rating', main=e$evaluationtype)

e <- evals[evals$evalname == 'Available Water Capacity <10cm', ]
res <- extractEvalCurve(e)
s <- seq(e$propmin, e$propmax, length.out = 25)
plot(s, res(s), type='l', xlab='domain', ylab='fuzzy rating', main=e$evaluationtype)



###
### Rules
###


# check a couple, RefId points to rows in rules or evaluation tables
# the dt$Do call links child sub-rules
# recursion is used to traverse to the deepest nodes, seems to work
# caution: don't run several times on the same object!

# increase limit argument to see the entire tree


## example
# just some random rule
y <- rules[rules$rulename == 'Dust PM10 and PM2.5 Generation', ]
dt <- parseRule(y)
# print intermediate results
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', limit=25)
# recusively splice-in sub-rules
dt$Do(traversal='pre-order', fun=linkSubRules)
# splice-in evaluation functions, if possible
dt$Do(traversal='pre-order', fun=linkEvaluationFunctions)
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', 'evalType', limit=25)


## more examples
y <- rules[rules$rulename == 'AGR - California Revised Storie Index (CA)', ]
dt <- parseRule(y)
dt$Do(traversal='pre-order', fun=linkSubRules)
dt$Do(traversal='pre-order', fun=linkEvaluationFunctions)
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', 'evalType', limit=25)


y <- rules[rules$rulename == 'Commodity Crop Productivity Index (Corn) (WI)', ]
dt <- parseRule(y)
dt$Do(traversal='pre-order', fun=linkSubRules)
dt$Do(traversal='pre-order', fun=linkEvaluationFunctions)
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', 'evalType', limit=25)



y <- rules[rules$rulename == 'DHS - Catastrophic Mortality, Large Animal Disposal, Pit', ]
dt <- parseRule(y)
dt$Do(traversal='pre-order', fun=linkSubRules)
dt$Do(traversal='pre-order', fun=linkEvaluationFunctions)
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', 'evalType', limit=25)


# this one has a single RuleEvaluation: RefId points to rows in evals table
y <- rules[rules$rulename == 'Clay %, in surface - MO2', ]
dt <- parseRule(y)
dt$Do(traversal='pre-order', fun=linkSubRules)
dt$Do(traversal='pre-order', fun=linkEvaluationFunctions)
print(dt, 'Type', 'Value', 'RefId', 'rule_refid', 'eval_refid', 'evalType', limit=25)


# check total number of nodes within data.tree object
dt$totalCount
```
